feat: add html viewer
viaacode/react-components pull request #102
Opened 2024-06-06 14:26 UTC by RobbeBierebeeck

…er-to-richtext-editor

feat: add html viewer

2024-06-11 14:59 UTC, bertyhell approved these changes

2024-06-12 15:08 UTC, ian-emsens-shd requested changes

2024-06-13 08:06 UTC, bertyhell approved these changes

2024-06-13 08:06 UTC, bertyhell commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +	foregroundColor,
these props match directly with the content block editor config values
so if we switch this to a generic styles prop, we'll need to modify the fields generator for content blocks which would make that system more complex
or we could also add a wrapper breadcrumb component that does the translation from foregroundColor => styles.color

both of these are too much work for the benefit of this block
if other styles are needed they will be exposed separatly using a separate prop and a separate control in the editor config of the block

2024-06-18 13:35 UTC, merged