feat(arc-1212): added meemooIdentifier to card
viaacode/react-components pull request #82
Opened 2023-03-14 09:01 UTC by WardVerc1

![image](https://user-images.githubusercontent.com/113892598/224949293-a06f6137-f20a-4c3e-ba28-c3e520abc287.png)
Ticket: https://meemoo.atlassian.net/browse/ARC-1212

2023-03-14 15:38 UTC, silkederudder-shd requested changes

2023-03-14 15:38 UTC, silkederudder-shd commented on src/components/Card/Card.tsx
> +				{subsubtitle && <div className={clsx(bem('subtitle-wrapper'))}>{subsubtitle}</div>}
Maybe use `caption` or `tagline` instead of `subsubtitle` ;)

2023-03-14 16:59 UTC, tourlbr approved these changes

2023-03-15 14:41 UTC, silkederudder-shd approved these changes

2023-03-15 14:42 UTC, merged